---
reporting:
  date: 'YYYY-MM-DD'
  title: '2024 DiseaseX Outbreak: CountryX [EXAMPLE]'
  introductory_text: 'This report provides an overview of the epidemiological situation of DiseaseX as reported by ReportingAgency as of DateEnd. The report includes information on the number of cases, deaths, and demographic characteristics of the affected population at different administrative levels. The report focuses on confirmed, probable, and suspected cases as defined by CountryX working case definitions published at CaseDefinitionLink. Note that the definitions are subject to change as the outbreak evolves.'
  data_range_inclusive:
    use_date: 'dateofnotification'
    start_date: null
    end_date: null
  provinces:
    include: null
    exclude: null
  zones_sante:
    include: null
    exclude: null
  aires_sante:
    include: null
    exclude: null
  html_template: 'report_template_v2.html'
  sections:
    ################################## Country-level, daily case number ##################################
    - type: 'text'
      parameters:
        content: 'Note that this is only an example report template. Figures shown below are generated using simulated data.'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 700
    - type: 'time-series-barplot'
      parameters:
        data:
          time_col: 'dateofnotification'
          deaths_only: false
          aggregate_by_epiweek: true
          moving_average_window: 3 # in units of aggregation (i.e. days or weeks)
          provinces:
            include: null
            exclude: null
          zones_sante:
            include: null
            exclude: null
          aires_sante:
            include: null
            exclude: null
        graphics:
          x_label: 'Date'
          y_label: 'Case Incidence'
          title: ''
          moving_average:
            show: true
            linewidth: 4
            colour: '#B4A269'
          fig_width: 1000
          fig_height: 400
          export: false
          filename: 'daily_case_incidence.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 1: Daily case incidence at country-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Province-level, daily case number ##################################
    - type: 'multi-province-time-series-barplot'
      parameters:
        data:
          time_col: 'dateofnotification'
          deaths_only: false
          aggregate_by_epiweek: true
          moving_average_window: 3 # in units of aggregation (e.g. days, weeks)
          provinces:
            include: null
            exclude: null
          zones_sante:
            include: null
            exclude: null
          aires_sante:
            include: null
            exclude: null
        graphics:
          tab_display: true
          x_label: 'Date'
          y_label: 'Case Incidence'
          title: ''
          moving_average:
            show: true
            linewidth: 4
            colour: '#B4A269'
          fig_width: 1000
          fig_height: 300
          export: false
          filename: 'daily_case_incidence.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 2: Daily case incidence at province-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Province-level, cumulative case number ##################################
    - type: 'province-map'
      parameters:
        data:
          time_col: 'dateofnotification'
          deaths_only: false
          date_range_inclusive:
            start_date: null
            end_date: null
        graphics:
          title: ''
          fig_width: 15
          fig_height: 15
          export: false
          filename: 'province_case_distribution_map.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 3: Cumulative case distribution at province-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Zone-sante-level, cumulative case number ##################################
    - type: 'zone-sante-map'
      parameters:
        data:
          time_col: 'dateofnotification'
          deaths_only: true
          date_range_inclusive:
            start_date: null
            end_date: null
        graphics:
          title: ''
          fig_width: 15
          fig_height: 15
          export: false
          filename: 'zone-sante_case_distribution_map.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 4: Cumulative case distribution at zone-sante-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Country-level, age-sex distribution ################################
    - type: 'age-sex-pyramid-plot'
      parameters:
        data:
          time_col: 'dateofnotification'
          deaths_only: false
          date_range_inclusive:
            start_date: null
            end_date: null
          age_col: 'age'
          age_groups: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
          sex_col: 'sex'
          provinces:
            include: null
            exclude: null
          zones_sante:
            include: null
            exclude: null
          aires_sante:
            include: null
            exclude: null
        graphics:
          x_label: 'Population'
          y_label: 'Age Group'
          title: ''
          fig_width: 1200
          fig_height: 500
          export: false
          filename: 'age-sex-distribution.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 5: Age-sex distribution at country-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Province-level, age-sex distribution ################################
    - type: 'multi-province-age-sex-pyramid-plot'
      parameters:
        data:
          time_col: 'dateofnotification'
          deaths_only: false
          date_range_inclusive:
            start_date: null
            end_date: null
          age_col: 'age'
          age_groups: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
          sex_col: 'sex'
          provinces:
            include: null
            exclude: null
          zones_sante:
            include: null
            exclude: null
          aires_sante:
            include: null
            exclude: null
        graphics:
          x_label: 'Population'
          y_label: 'Age Group'
          title: ''
          fig_width: 1200
          fig_height: 500
          export: false
          filename: 'age-sex-distribution.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 6: Age-sex distribution at province-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Province-level, weekly cumulative case distribution ################################
    - type: 'multi-week-province-map'
      parameters:
        data:
          time_col: 'dateofnotification'
          deaths_only: true
          weeks: ['2023-02-05', '2023-02-12', '2023-02-19', '2023-02-26']
        graphics:
          title: ''
          fig_width: 20
          fig_height: 20
          export: false
          filename: 'zone-sante_case_distribution_map.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 7: Weekly cumulative case distribution at province-level (4 weeks)'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Zone-sante-level, weekly cumulative case distribution ################################
    - type: 'multi-week-zone-sante-map'
      parameters:
        data:
          time_col: 'dateofnotification'
          deaths_only: true
          weeks: ['2023-02-05', '2023-02-12', '2023-02-19', '2023-02-26']
        graphics:
          title: ''
          fig_width: 20
          fig_height: 20
          export: false
          filename: 'zone-sante_case_distribution_map.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 8: Weekly cumulative case distribution at zone-sante-level (4 weeks)'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100



