---
reporting:
  date: '2023-10-01'
  title: 'DRC Mpox Outbreak Report'
  introductory_text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
  data_range_inclusive:
    use_date: 'date_notification'
    start_date: null
    end_date: null
  provinces:
    include: null
    exclude: null
  zones_sante:
    include: null
    exclude: null
  aires_sante:
    include: null
    exclude: null
  sections:
    ################################## Country-level, daily case number ##################################
    - type: 'time-series-barplot'
      parameters:
        data:
          time_col: 'date_notification'
          deaths_only: false
          aggregate_by_epiweek: true
          moving_average_window: 3 # in units of aggregation (e.g. days, weeks)
          provinces:
            include: null
            exclude: null
          zones_sante:
            include: null
            exclude: null
          aires_sante:
            include: null
            exclude: null
        graphics:
          x_label: 'Date'
          y_label: 'Case Incidence'
          title: ''
          moving_average:
            show: true
            linewidth: 4
            colour: '#B4A269'
          fig_width: 1000
          fig_height: 400
          export: false
          filename: 'daily_case_incidence.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 1: Daily case incidence at country-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Province-level, daily case number ##################################
    - type: 'multi-province-time-series-barplot'
      parameters:
        data:
          time_col: 'date_notification'
          deaths_only: false
          aggregate_by_epiweek: true
          moving_average_window: 3 # in units of aggregation (e.g. days, weeks)
          provinces:
            include: null
            exclude: null
          zones_sante:
            include: null
            exclude: null
          aires_sante:
            include: null
            exclude: null
        graphics:
          x_label: 'Date'
          y_label: 'Case Incidence'
          title: ''
          moving_average:
            show: true
            linewidth: 4
            colour: '#B4A269'
          fig_width: 1000
          fig_height: 300
          export: false
          filename: 'daily_case_incidence.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 2: Daily case incidence at province-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Province-level, cumulative case number ##################################
    - type: 'province-map'
      parameters:
        data:
          time_col: 'date_notification'
          deaths_only: false
          date_range_inclusive:
            start_date: null
            end_date: null
        graphics:
          title: ''
          fig_width: 15
          fig_height: 15
          export: false
          filename: 'province_case_distribution_map.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 3: Cumulative case distribution at province-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Zone-sante-level, cumulative case number ##################################
    - type: 'zone-sante-map'
      parameters:
        data:
          time_col: 'date_notification'
          deaths_only: true
          date_range_inclusive:
            start_date: null
            end_date: null
        graphics:
          title: ''
          fig_width: 15
          fig_height: 15
          export: false
          filename: 'zone-sante_case_distribution_map.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 4: Cumulative case distribution at zone-sante-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Country-level, age-sex distribution ################################
    - type: 'age-sex-pyramid-plot'
      parameters:
        data:
          time_col: 'date_notification'
          deaths_only: false
          date_range_inclusive:
            start_date: null
            end_date: null
          age_col: 'age'
          age_groups: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
          sex_col: 'sex'
          provinces:
            include: null
            exclude: null
          zones_sante:
            include: null
            exclude: null
          aires_sante:
            include: null
            exclude: null
        graphics:
          x_label: 'Population'
          y_label: 'Age Group'
          title: ''
          fig_width: 1200
          fig_height: 500
          export: false
          filename: 'age-sex-distribution.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 5: Age-sex distribution at country-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Province-level, age-sex distribution ################################
    - type: 'multi-province-age-sex-pyramid-plot'
      parameters:
        data:
          time_col: 'date_notification'
          deaths_only: false
          date_range_inclusive:
            start_date: null
            end_date: null
          age_col: 'age'
          age_groups: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
          sex_col: 'sex'
          provinces:
            include: null
            exclude: null
          zones_sante:
            include: null
            exclude: null
          aires_sante:
            include: null
            exclude: null
        graphics:
          x_label: 'Population'
          y_label: 'Age Group'
          title: ''
          fig_width: 1200
          fig_height: 500
          export: false
          filename: 'age-sex-distribution.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 6: Age-sex distribution at province-level'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Province-level, weekly cumulative case distribution ################################
    - type: 'multi-week-province-map'
      parameters:
        data:
          time_col: 'date_notification'
          deaths_only: true
          weeks: ['2023-02-05', '2023-02-12', '2023-02-19', '2023-02-26']
        graphics:
          title: ''
          fig_width: 20
          fig_height: 20
          export: false
          filename: 'zone-sante_case_distribution_map.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 7: Weekly cumulative case distribution at province-level (4 weeks)'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100
    - type: 'horizontal-line'
    ######################################################################################################
    ################################## Zone-sante-level, weekly cumulative case distribution ################################
    - type: 'multi-week-zone-sante-map'
      parameters:
        data:
          time_col: 'date_notification'
          deaths_only: true
          weeks: ['2023-02-05', '2023-02-12', '2023-02-19', '2023-02-26']
        graphics:
          title: ''
          fig_width: 20
          fig_height: 20
          export: false
          filename: 'zone-sante_case_distribution_map.pdf'
    - type: 'text'
      parameters:
        content: 'Fig. 8: Weekly cumulative case distribution at zone-sante-level (4 weeks)'
        text_color: '#484848'
        font_size: '15px'
        font_weight: 100



